struct: struct.c
	gcc -Wall -std=c99 -o struct struct.c

define-struct: define-struct.c
	gcc -Wall -std=c99 -o define-struct define-struct.c

struct-array: struct-array.c
	gcc -Wall -std=c99 -o struct-array struct-array.c

dictionay: dictionary.c
	gcc -Wall -std=c99 -o dictionary dictionary.c

enum: enum.c
	gcc -Wall -std=c99 -o enum enum.c

clean:
	rm -f *.o
