wordSearch2D:./src/wordSearch2D.c ./src/error_checking.c ./src/puzzle2D.c
	gcc -Wall -Wextra -Werror -std=c99 ./src/wordSearch2D.c ./src/error_checking.c ./src/puzzle2D.c -o wordSearch2D

clean:
	rm -rf *.o wordSearch2D core
