float: float.c
	gcc -Wall -std=c99 -o float float.c

integer: integer.c
	gcc -Wall -std=c99 -o integer integer.c

read_char: read_char.c
	gcc -Wall -std=c99 -o read_char read_char.c

types: types.c
	gcc -Wall -std=c99 -o types types.c 

var-length-array: var-length-array.c
	gcc -Wall -std=c99 -o var-length-array var-length-array.c

clean:
	rm -f float integer read_char types var-length-array
