square-loops: square-do-while square-for-loop square-while

square-do-while: square-do-while.c
	gcc -Wall -std=c99 square-do-while.c -o square-do-while

square-for-loop: square-for-loop.c
	gcc -Wall -std=c99 square-for-loop.c -o square-for-loop

square-while: square-while.c
	gcc -Wall -std=c99 square-while.c -o square-while

convert: convert.c
	gcc -Wall -std=c99 -o convert convert.c

break-continue: break-continue.c
	gcc -Wall -std=c99 -o break-continue break-continue.c

clean:
	rm -f convert break-continue core square-do-while square-for-loop square-while
